### ISSUE TITLE
Project information 

### ISSUE THREAD

**Issue by phamthanhhang208** [pinezapple/LibraryProject20201#1]
Documentation working in progress

**Comment by pinezapple** [comment]
Requirements determination phase is in progress

**Comment by pinezapple** [comment]
Done with Usecases determination

**Comment by pinezapple** [comment]
Done with Communication, ER, Class Diagram.

**Comment by pinezapple** [comment]
Created Skeleton reusable code for future use config

**Comment by pinezapple** [comment]
Added first version of docmanager

**Comment by pinezapple** [comment]
Added etcdConfigs.

**Comment by pinezapple** [comment]
Added new system overall documents, wait for approval

**Comment by pinezapple** [comment]
portal service in progress
